---
title: "DS6372Project1"
author: "Andre Mauldin"
date: "1/24/2021"
output: html_document
---
### Project 1

### Libraries
```{r}
library(leaps)
library(magrittr) # makes the pipe %>% work
library(ggplot2)
library(tidyverse)
library(reshape2)
library(car)     # where vif function lives
library(ISLR)
library(leaps)
library(dplyr)
library(doBy)
library(e1071)
library(class)
library(caret)
library(Metrics)
library(gtools)
library(glmnet)
library(arm)
```

### Data
```{r}
options(digits = 10, scipen = 2) # removes scientific notation and goes to 10 decimal places

CaseData = read.csv('data1.csv',header = T,sep = ",", stringsAsFactors = TRUE)
# view(CaseData) # shows the whole data set
head(CaseData) # shows the first 6 rows
```
```{r, fig.height=25, fig.width=25}
pairs(CaseData[1:8]) # -c(column to exclude 1, column to exclude 2, and so on....) 
pairs(CaseData)
t(aggregate(MSRP~Engine.Cylinders,data=CaseData,summary))
```


### Data Prep
```{r}
isEmpty <- function(column) {
    is.na(column) | column == 0 | column == "" | column == " " | column == "NA" | column == "na" | column == "Na" | column == "nA" | column == "NaN" 
}

#Filter out old cars
CaseData %>% filter(MSRP > 2000) -> CaseData.NewCars.1

CaseData.NewCars = data.frame(CaseData.NewCars.1, stringsAsFactors = TRUE)

# filter Fuel.Type
CaseData.NewCars %>% filter(!isEmpty(Engine.Fuel.Type) & Engine.Fuel.Type != "natural gas") -> CaseData.NewCars.Filtered

# Set missing horsepower, Cylinders, and Doors to the median of each by size
# First we filter to get values to set variables for the median of each
# Horsepower
Vehicle.Size.Summary <- CaseData.NewCars.Filtered %>% filter(!isEmpty(Engine.HP)) %>% group_by(Vehicle.Size) %>%  summarise(median_hp_by_vehicle_size=median(Engine.HP))
Vehicle.Size.Summary
# Cylinders
Vehicle.Size.Summary <- CaseData.NewCars.Filtered %>% filter(!isEmpty(Engine.Cylinders)) %>% group_by(Vehicle.Size) %>%  summarise(median_cylinders_by_vehicle_size=median(Engine.Cylinders))
Vehicle.Size.Summary
# Doors
Vehicle.Size.Summary <- CaseData.NewCars.Filtered %>% filter(!isEmpty(Number.of.Doors)) %>% group_by(Vehicle.Size) %>%  summarise(median_doors_by_vehicle_size=median(Number.of.Doors))
Vehicle.Size.Summary

# Median horsepower by size based on Vehicle.Size.Summary
compact.hp.median = 180
large.hp.median = 310
midsize.hp.median = 250
# Median cylinders by size based on Vehicle.Size.Summary
compact.cyl.median = 4
large.cyl.median = 6
midsize.cyl.median = 6
# Here we set the NAs to the median by size in new columns called Engine.HP.Clean, Engine.Cylinders.Clean, Number.of.Doors.Clean
CaseData.NewCars.Filtered.Impuded <- CaseData.NewCars.Filtered %>%
  mutate(
    Engine.HP.Clean =
    ifelse(isEmpty(Engine.HP) & Vehicle.Size == "Compact", compact.hp.median,
           ifelse(isEmpty(Engine.HP) & Vehicle.Size == "Large", large.hp.median,
                  ifelse(isEmpty(Engine.HP) & Vehicle.Size == "Midsize", midsize.hp.median, Engine.HP))),
    Engine.Cylinders.Clean =
    ifelse(isEmpty(Engine.Cylinders) & Vehicle.Size == "Compact", compact.cyl.median,
           ifelse(isEmpty(Engine.Cylinders) & Vehicle.Size == "Large", large.cyl.median,
                  ifelse(isEmpty(Engine.Cylinders) & Vehicle.Size == "Midsize", midsize.cyl.median, Engine.Cylinders))),
    Number.of.Doors.Clean = ifelse(isEmpty(Number.of.Doors), 4, Number.of.Doors)
  )

# Shows results of our cleaned columns
# Horsepower
CaseData.NewCars.Filtered.Impuded %>% select(Vehicle.Size, Engine.HP, Engine.HP.Clean) %>% filter(isEmpty(Engine.HP))
# Cylinders
CaseData.NewCars.Filtered.Impuded %>% select(Vehicle.Size, Engine.Cylinders, Engine.Cylinders.Clean) %>% filter(isEmpty(Engine.Cylinders))
# Doors
CaseData.NewCars.Filtered.Impuded %>% select(Vehicle.Size, Number.of.Doors, Number.of.Doors.Clean) %>% filter(isEmpty(Number.of.Doors))

# Cleaned Data Set
CaseData
CaseData.NewCars.Filtered.Impuded 
```
## Summary of Data Before and After Impuding (Data Prep Continued)
```{r}
# This can be placed in the main document
# Summary of Data Before and After Impuding
df <- data.frame(
  Horsepower = matrix(summary(CaseData.NewCars.Filtered.Impuded[5])),
  HorsepowerClean = c(matrix(summary(CaseData.NewCars.Filtered.Impuded[17])),"-"),
  Cylinders = matrix(summary(CaseData.NewCars.Filtered.Impuded[6])),
  CylindersClean = c(matrix(summary(CaseData.NewCars.Filtered.Impuded[18])),"-"),
  Doors =	matrix(summary(CaseData.NewCars.Filtered.Impuded[9])),
  DoorsClean = c(matrix(summary(CaseData.NewCars.Filtered.Impuded[19])),"-")
)%>%
 kbl() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), font_size = 12)%>%
    add_header_above(c("Summary Data Continued" = 6))
df
```

```{r, fig.height=25, fig.width=25}
# This can be placed in the appendix
CaseDataSummary <- data.frame(
  MSRP = c(matrix(summary(CaseData[16])), "-"),
  Make = matrix(summary(CaseData[1])),
  Model =	matrix(summary(CaseData[2])),
  Year = c(matrix(summary(CaseData[3])), "-"),
  Fuel_Type = matrix(summary(CaseData[4])),
  Horsepower = matrix(summary(CaseData[5])),
  HorsepowerClean = c(matrix(summary(CaseData.NewCars.Filtered.Impuded[17])),"-"),
  Cylinders = matrix(summary(CaseData[6])),
  CylindersClean = c(matrix(summary(CaseData.NewCars.Filtered.Impuded[18])),"-"),
  Transmission =	c(matrix(summary(CaseData[7])),"-","-")
)%>%
 kbl() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), font_size = 10) %>%
    add_header_above(c("Summary Data" = 10))

CaseDataSummary2 <- data.frame(
  Driven_Wheels =	c(matrix(summary(CaseData[8])),"-","-","-"),
  Doors =	matrix(summary(CaseData[9])),
  DoorsClean = c(matrix(summary(CaseData.NewCars.Filtered.Impuded[19])),"-"),
  Market_Category =	matrix(summary(CaseData[10])),
  Size = c(matrix(summary(CaseData[11])),"-","-","-","-"),
  Style =	matrix(summary(CaseData[12])),
  HWY_MPG =	c(matrix(summary(CaseData[13])),"-"),
  City_MPG = c(matrix(summary(CaseData[14])),"-"),
  Popularity = c(matrix(summary(CaseData[15])),"-")
)%>%
 kbl() %>%
  kable_styling(bootstrap_options = c("striped", "hover"), font_size = 12)%>%
    add_header_above(c("Summary Data Continued" = 9))

CaseDataSummary
CaseDataSummary2
```
The differences in values for horsepower, cylinders, and doors are minor after imputing.

# Feature Selection

```{r}
glimpse(CaseData.NewCars.Filtered.Impuded)
# CaseData.NewCars.Filtered.Impuded[,-c(5,6,9)] -> A
CaseData.NewCars.Filtered.Impuded[,c('Make','Model','Year','Engine.Fuel.Type','Transmission.Type','Driven_Wheels','Market.Category','Vehicle.Size','Vehicle.Style','highway.MPG','city.mpg','Popularity','MSRP','Engine.HP.Clean','Engine.Cylinders.Clean','Number.of.Doors.Clean'  )] -> A
SplitPerc = .80
set.seed(12)

TrainIndices = sample(1:dim(A)[1],round(SplitPerc * dim(A)[1]))
train = A[TrainIndices,]
test = A[-TrainIndices,]

#Formatting data for GLM net
x=model.matrix(MSRP~.,train)[,-1]
y=log(train$MSRP)

xtest<-model.matrix(MSRP~.,test)[,-1]
ytest<-log(test$MSRP)

grid=10^seq(10,-2, length =100)
lasso.mod=glmnet(x,y,alpha=1, lambda =grid)

cv.out=cv.glmnet(x,y,alpha=1) #alpha=1 performs LASSO
plot(cv.out)
bestlambda<-cv.out$lambda.min  #Optimal penalty parameter.  You can make this call visually.
lasso.pred=predict (lasso.mod ,s=bestlambda ,newx=xtest)

testMSE_LASSO<-mean((ytest-lasso.pred)^2)
testMSE_LASSO

```

```{r,echo=T}
SplitPerc = .80
SplitPerc2 = .50
CaseData.NewCars.Filtered.Impuded -> A # A is the alias for impuded data

TrainIndices = sample(1:dim(A)[1],round(SplitPerc * dim(A)[1]))
train = A[TrainIndices,]

B = A[-TrainIndices,]

TestValIndicies = sample(1:dim(B)[1],round(SplitPerc2 * dim(B)[1]))
test = B[TestValIndicies,]
validate = B[-TestValIndicies,]
```

```{r, fig.height=5, fig.width=10}
CaseData.NewCars.Filtered.Impuded -> A
par(mfrow=c(2,2))
CaseModel<-lm(
  MSRP~Year+highway.MPG+city.mpg+Popularity+Engine.HP.Clean+
    Engine.Cylinders.Clean+Number.of.Doors.Clean,data=A
)
CaseModel.Log<-lm(log(MSRP)~Year+highway.MPG+city.mpg+Popularity+Engine.HP.Clean+
    Engine.Cylinders.Clean+Number.of.Doors.Clean,data=A)
plot(CaseModel)
vif(CaseModel)#[,3]^2 # displays [,3] column 3 horizintally and '^2' squares the values

##Histogram
CaseModelRes <- rstudent(CaseModel.Log)
hist(CaseModelRes, freq=FALSE, main="Distribution of Residuals",
xlab="Studentized Residuals", ylab="Density")
##Create range of x-values for normal curve
xCaseModelRes <- seq(min(CaseModelRes), max(CaseModelRes), length=40)
##Generate values from the normal distribution at the specified values
yCaseModelRes <- (dnorm(CaseModelRes))
##Add the normal curve
lines(xCaseModelRes, yCaseModelRes) # ylim=c(0,0.5)
#cook's D and leverage
par(mfrow=c(1,2))
ols_plot_cooksd_chart(CaseModel)
ols_plot_resid_lev(CaseModel)
```
